language: python

matrix:
  include:
    - python: 3.5
      env:
        - COVERAGE=false
        - EXTRATESTERS=""
        - ARGS=""
    - python: 3.6
      env:
        - COVERAGE=true
        - EXTRATESTERS=""
        - ARGS=""
    - python: 3.7
      env:
        - COVERAGE=true
        - EXTRATESTERS=""
        - ARGS="--pep8 --mpl"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda install --yes nomkl

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION numpy matplotlib docopt requests pyyaml
  - source activate test
  - conda install --yes --channel=conda-forge pytest-mpl pytest-cov pytest-pep8 ${EXTRATESTERS}
  - if [ ${COVERAGE} = true ]; then conda install scipy --yes; fi
  - pip install codecov
  - pip install .

script:
  - coverage run --source probscale check_probscale.py --verbose ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      codecov;
    fi
